title: Oxlip API Language
email: info@oxlip-lang.org
description: >-
  Documentation for the Oxlip API language.
baseurl: ""
url: "https://doc.oxlip-lang.org"
source: ./src
destination: ./build

theme: just-the-docs
color_scheme: oxlip

aux_links:
  "OAL on GitHub":
    - "//github.com/oxlip-lang/oal"

aux_links_new_tab: true

nav_external_links:
  - title: OAL on GitHub
    url: https://github.com/oxlip-lang/oal
